version: '3.8'
services:

    #PHP Service
    iq_devs_main_fpm:
        build:
            context: ./php
            dockerfile: ./Dockerfile
        image: iq_devs_main_fpm
        container_name: iq_devs_main_fpm
        restart: unless-stopped
        tty: true
        env_file:
            - ../.env
        working_dir: /var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ../:/var/www
        networks:
            - iq_devs_main-network


    #Supervisor Service
    iq_devs_main_supervisor:
        build:
            context: ./php
            dockerfile: ./Dockerfile
        image: iq_devs_main_supervisor
        container_name: iq_devs_main_supervisor
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        command: bash -c "printenv | sed 's/^\(.*\)$$/export \1/g' > /root/project_env.sh && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf"
        env_file:
            - ../.env
        working_dir: /var/www
        volumes:
            - ../:/var/www
        networks:
            - iq_devs_main-network

    #Nginx Service
    iq_devs_main:
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        image: iq_devs_main
        container_name: iq_devs_main
        restart: unless-stopped
        tty: true
        ports:
            - "7080:80"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - iq_devs_main-network

    #MySQL Service
    iq_devs_main_db:
        image: mariadb
        container_name: iq_devs_main_db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - /var/lib/mysql_main:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - iq_devs_main-network

#Docker Networks
networks:
    iq_devs_main-network:
        driver: bridge
